name: 'AI Code Review Bot'
description: 'Automatically reviews pull requests using Google Gemini AI'
author: 'Your Name'
branding:
  icon: 'check-circle'
  color: 'blue'

inputs:
  gemini_api_key:
    description: 'Gemini API key for AI reviews'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
