name: 'CodeBuddy AI'
description: 'Your friendly AI code reviewer powered by Google Gemini'
author: 'Your Name'
branding:
  icon: 'check-circle'
  color: 'blue'

inputs:
  gemini_api_key:
    description: 'Gemini API key for AI reviews'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install dependencies
      shell: bash
      run: |
        cd ${{ github.action_path }}
        npm ci
    
    - name: Build action
      shell: bash
      run: |
        cd ${{ github.action_path }}
        npm run build
    
    - name: Run CodeBuddy AI
      shell: bash
      env:
        INPUT_GEMINI_API_KEY: ${{ inputs.gemini_api_key }}
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        cd ${{ github.action_path }}
        node dist/index.js
